# Start
#   docker compose -f lab-compose.yml up
# View specific containers
#   docker attach tryspace-fsw
#   docker attach tryspace-comp-demo-sim
#   docker attach tryspace-sim
services:
  tryspace-sim:
    image: tryspace-sim:latest
    container_name: tryspace-sim
    networks:
      - tryspace-net
    restart: unless-stopped
    stdin_open: true
    tty: true

  #tryspace-comp-demo-sim:
  #  image: tryspace-comp-demo-sim:latest
  #  container_name: tryspace-comp-demo-sim
  #  networks:
  #    - tryspace-net
  #  restart: unless-stopped
  #  depends_on:
  #    - tryspace-sim

  tryspace-fsw:
    image: tryspace-fsw:latest
    container_name: tryspace-fsw
    networks:
      - tryspace-net
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - tryspace-sim
    #  - tryspace-comp-demo-sim
    sysctls:
      - fs.mqueue.msg_max=10000
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_NICE
    #command: >
    #  sh -c "touch /app/.cdskeyfile /app/.resetkeyfile /app/.reservedkeyfile && 
    #         /app/core-cpu1"

networks:
  tryspace-net:
    driver: bridge
