# Start
#   docker compose -f lab-compose.yml up
# View specific containers
#   docker attach tryspace-fsw
#   docker attach tryspace-comp-demo-sim
#   docker attach tryspace-sim
services:
  tryspace-sim:
    image: tryspace-sim:latest
    container_name: tryspace-sim
    networks:
      - tryspace-net
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - NUM_CLIENTS=${NUM_CLIENTS:-2}
    command: ["/bin/sh", "-c", "/app/simulith_server_standalone $${NUM_CLIENTS}"]

  tryspace-comp-demo-sim:
    image: tryspace-comp-demo-sim:latest
    container_name: tryspace-comp-demo-sim
    networks:
      - tryspace-net
    restart: unless-stopped
    depends_on:
      - tryspace-sim

  tryspace-fsw:
    image: tryspace-fsw:latest
    container_name: tryspace-fsw
    networks:
      - tryspace-net
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - tryspace-sim
      - tryspace-comp-demo-sim
    sysctls:
      - fs.mqueue.msg_max=10000
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_NICE
    
networks:
  tryspace-net:
    driver: bridge
