name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-simulith:
    runs-on: ubuntu-latest
    container:
        image: tryspaceorg/tryspace-lab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build Simulith
        run: |
          cd simulith && make build-sim

  build-fsw:
    runs-on: ubuntu-latest
    container:
        image: tryspaceorg/tryspace-lab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build FSW
        run: |
          cd fsw && make build-fsw
